---
- name: Install pip - Debian
  apt:
    name: "{{ pip_packages_ubuntu|default(omit) }}"
    state: latest
    force: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int < 20
    
- name: Install pip - Ubuntu 20.04
  apt:
    name: "{{ pip_packages_ubuntu_20|default(omit) }}"
    state: latest
    force: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int >= 20

- name: Install pip - Archlinux
  pacman:
    state: latest
    name: "{{ pip_packages_arch|default(omit) }}"
  when: ansible_os_family == "Archlinux"

- name: Install pip packages
  pip:
    name: "{{ pip_custom_packages|default(omit) }}"
    state: present
    executable: pip3
  when: pip_custom_packages is defined

- name: Upgrade pip centos
  dnf:
    name: python3-pip
    state: latest
  when: ansible_os_family == "RedHat"
